version: "3"
services:
  postgres:
    image: "postgres:latest"
    # For Error: https://stackoverflow.com/questions/60420940/how-to-fix-error-error-database-is-uninitialized-and-superuser-password-is-not
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: "redis:latest"
  express_server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
  client:
    # To mitigate the Error: https://dev.to/igmrrf/docker-react-exited-with-code-0-398n
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4040:80"
    restart: always